# vserv.yml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: nginx-virtualservice
  namespace: istio-system
  
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - match:
        - uri:
            prefix: /  # Match all URIs
      route:
        - destination:
            host: nginx-lb.nginx.svc.cluster.local
            port:
              number: 80